[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "random-quote-retriever"
version = "0.2.1"
description = "A simple CLI tool to fetch random quotes from the ZenQuotes API"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [{ name = "Muhammad Hasan" }]
dependencies = [
  "requests>=2.32.3",
  "platformdirs>=4.0",
]

[project.scripts]
quote = "random_quote_retriever.cli:main"

[tool.setuptools]
packages = ["random_quote_retriever"]
